description: Dependable and Secure Autonomous Systems â€” Space and Drone/UAV Technologies in the Age of AI
theme: jekyll-theme-tactile
showdownloads: false

baseurl: ""
url: "https://dsas2026.github.io"

